### ISSUE TITLE
Issue in accessing bit bucket server Visual Studio Bit bucket Extension - Request line is too large

### ISSUE THREAD

**Issue by mukunthan** [MistyKuu/bitbucket-for-visual-studio#30]
I tried to access company bit bucket account using bit bucket sever option, I'm getting below error.
![bitbucket](https://user-images.githubusercontent.com/7686885/30122464-2970ccb2-934c-11e7-99e8-88450f408130.JPG)
Do you have any idea?  Is it related with any app access privilege of user?

It would be helpful if you let me ow the possible cause for this error.

**Comment by MistyKuu** [comment]
I don't have much time now but it looks like it's again because it cannot get recent repositories. I use this endpoint to validate the connection but it was a wrong choice. If you look into logs you'll see this:

```2017-08-31 21:46:15,587 [1] INFO  BitBucket.REST.API.Wrappers.BitbucketRestClientBase [(null)] - Calling ExecuteTaskAsync. BaseUrl: https://mukunthant@bitbucket.org/techerupt/rest/api/1.0 Resource: profile/recent/repos
2017-08-31 21:46:29,296 [1] ERROR BitBucket.REST.API.Serializers.NewtonsoftJsonSerializer [(null)] - 
Couldn't deserialize json: <html>
  <head>
    <title>Bad Request</title>
  </head>
  <body>
    <h1><p>Bad Request</p></h1>
    **Request Line is too large (4386 &gt; 4094)**
  </body>
</html>
. Error: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
```

It seems like your recent repositories list is too big to handle it. I have to increase request size. In the meantime you can try to clean this list somehow however I don't know if it's possible.

**Comment by MistyKuu** [comment]
After further investigation it seems that it's something that has to be configured in your server. I'm closing it for now, please reopen it in case of any issues.
