### ISSUE TITLE
Colors of review code screen in dark VS are incorrect

### ISSUE THREAD

**Issue by szymonbe** [MistyKuu/bitbucket-for-visual-studio#4]
Steps
1. Open Visual studio in dark mode
2. Open extension to browse pull requests and select one
3. Open any file,  with changes,  to check
4. Check the colors

Actual
All colors in the screen make eyes painful, especially red, green and blue. (Dark scheme of visual studio)
All line is highlighted in the same way so user has to compare and search for the change e.g. only one word or character in the line.

Expected
Please have a look at colors in changes in Visual studio, highlighting of a line is much more subtle
In addition there is added parsing of changing so the changes word in a line ix extra highlighted which improves code review

**Comment by MistyKuu** [comment]
Thank you for submitting the issue.
Yes, I agree that it looks terribly with Dark Theme. I'll try to figure out if there is a way to use VS themes. Regarding the second request at a first glance it should be easy to implement. I'll include these changes with side-by-side diff feature together.

**Comment by MistyKuu** [comment]
1. Colors have been changed to match VS themes however I had to get rid of syntax highlighting because it didn't look well for some formats i.e xml.
2. I've also added Side by Side diff, built in feature from VS - it contains changes highlighting on word level. 
3. I've also tried to add word highlighting in Inline diff view but without a success so I will have to do it in the nearest future.

The changes will be deployed in the next version.
